version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHID=${CHID}
      - SUDO=${SUDO}
      - FSUB=${FSUB}
      - MONGO_URI=${MONGO_URI}
      - REQUIRED_CHANNELS=${REQUIRED_CHANNELS}
      - BOT_NAME=${BOT_NAME}
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_VERSION=${BOT_VERSION}
      - LOG_LEVEL=${LOG_LEVEL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - RATE_LIMIT=${RATE_LIMIT}
      - ENABLE_BROADCAST=${ENABLE_BROADCAST}
      - ENABLE_CHANNEL_CHECK=${ENABLE_CHANNEL_CHECK}
    command: python3 bot.py
    restart: always
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 512Mi
    volumes:
      - ./data:/app/data

volumes:
  data:
